version: '3.5'

services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    networks:
      - Inception
    restart: always
    env_file:
      - .env
    volumes:
      - mariadb-vol:/var/lib/mysql

  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    networks:
      - Inception
    restart: always
    ports:
      - 80:80

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    networks:
      - Inception
    restart: always

networks:
  Inception:
    name: Inception

volumes:
  mariadb-vol:
    name: mariadb-volume
    driver_opts:
      device: /home/jrinna/data/mariadb
      type: volume
      o: bind