version: '3.5'

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    networks:
      - Inception
    restart: always
    env_file:
      - .env
    volumes:
      - mariadb-vol:/var/lib/mysql

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    networks:
      - Inception
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    networks:
      - Inception
    restart: always

networks:
  Inception:
    name: Inception

volumes:
  mariadb-vol:
    name: mariadb-volume
    driver_opts:
      device: /home/jrinna/volume/mariadb
      type: volume
      o: bind